# Generated by Django 3.1.7 on 2021-12-02 00:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres de Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/contacts/', verbose_name='Imagen')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('watsap', models.CharField(blank=True, max_length=11, null=True, verbose_name='Watsap')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electónico')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Referencia')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria activada/Categoria no activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Nombre')),
                ('sterilization', models.BooleanField(default=True, verbose_name='Esterilizdo/No Esterilizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Garantiza esterilización/No garantiza esterilización')),
                ('direction', models.CharField(max_length=255, verbose_name='Dirección')),
                ('sex', models.CharField(blank=True, choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=50, null=True, verbose_name='Sexo')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagen url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/pets/', verbose_name='Imagen')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
                ('dado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
